import { LupProject, OrgUnit } from './org.model';

export const ORG_UNITS: OrgUnit[] = [
  { id: 'dir-data', name: 'Diretoria de Dados', level: 'diretoria', branch: 'technology' },
  { id: 'sup-platform', name: 'Superintendencia Plataforma', level: 'superintendencia', branch: 'technology', parentId: 'dir-data' },
  { id: 'mgmt-data-platform', name: 'Gerencia Data Platform', level: 'gerencia', branch: 'technology', parentId: 'sup-platform' },
  { id: 'coord-core-data', name: 'Coordenacao Core Data', level: 'coord', branch: 'technology', parentId: 'mgmt-data-platform' },
  { id: 'coord-analytics', name: 'Coordenacao Analytics Engineering', level: 'coord', branch: 'technology', parentId: 'mgmt-data-platform' },
  { id: 'squad-a', name: 'Squad A', level: 'squad', branch: 'technology', parentId: 'coord-core-data' },
  { id: 'squad-b', name: 'Squad B', level: 'squad', branch: 'technology', parentId: 'coord-analytics' },
  { id: 'squad-c', name: 'Squad C', level: 'squad', branch: 'technology', parentId: 'coord-core-data' },

  { id: 'dir-business', name: 'Diretoria Negocios Digitais', level: 'diretoria', branch: 'business' },
  { id: 'sup-revenue', name: 'Superintendencia Receita', level: 'superintendencia', branch: 'business', parentId: 'dir-business' },
  { id: 'mgmt-commercial', name: 'Gerencia Comercial', level: 'gerencia', branch: 'business', parentId: 'sup-revenue' },
  { id: 'coord-crm', name: 'Coordenacao CRM', level: 'coord', branch: 'business', parentId: 'mgmt-commercial' },
];

export const LUP_PROJECTS: LupProject[] = [
  {
    id: 'lup-ed-2741',
    code: 'ED2741',
    type: 'ED',
    name: 'customer_360',
    description: 'Visao consolidada de cliente para Marketing e CS.',
    squadId: 'squad-b',
    owner: 'Squad B',
    status: 'waiting_approval',
    health: 'yellow',
    progress: 27,
    pipelineCount: 3,
    monthlyCost: 18400,
    updatedAt: '2026-04-26T09:20:00-03:00',
    linkedProjectIds: ['lup-ea-1180'],
  },
  {
    id: 'lup-ed-2736',
    code: 'ED2736',
    type: 'ED',
    name: 'risk_exposure_daily',
    description: 'Pipeline diaria de exposicao de risco por carteira.',
    squadId: 'squad-c',
    owner: 'Squad C',
    status: 'in_progress',
    health: 'gray',
    progress: 64,
    pipelineCount: 2,
    monthlyCost: 22100,
    updatedAt: '2026-04-26T08:02:00-03:00',
    linkedProjectIds: [],
  },
  {
    id: 'lup-ed-2719',
    code: 'ED2719',
    type: 'ED',
    name: 'finance_curated_v2',
    description: 'Curadoria financeira e publicacao em RDS reporting.',
    squadId: 'squad-c',
    owner: 'Squad C',
    status: 'blocked',
    health: 'red',
    progress: 95,
    pipelineCount: 4,
    monthlyCost: 37600,
    updatedAt: '2026-04-25T18:12:00-03:00',
    linkedProjectIds: ['lup-ea-1177'],
  },
  {
    id: 'lup-ed-2708',
    code: 'ED2708',
    type: 'ED',
    name: 'orders_bronze_rebuild',
    description: 'Reprocessamento e nova ingestao da camada bronze de pedidos.',
    squadId: 'squad-a',
    owner: 'Squad A',
    status: 'in_production',
    health: 'green',
    progress: 100,
    pipelineCount: 5,
    monthlyCost: 12800,
    updatedAt: '2026-04-24T11:40:00-03:00',
    linkedProjectIds: [],
  },
  {
    id: 'lup-ea-1180',
    code: 'EA1180',
    type: 'EA',
    name: 'customer_segmentation',
    description: 'Modelo analitico de segmentacao de clientes.',
    squadId: 'squad-b',
    owner: 'Analytics',
    status: 'draft',
    health: 'gray',
    progress: 12,
    pipelineCount: 1,
    monthlyCost: 4200,
    updatedAt: '2026-04-22T17:30:00-03:00',
    linkedProjectIds: ['lup-ed-2741'],
  },
  {
    id: 'lup-ea-1177',
    code: 'EA1177',
    type: 'EA',
    name: 'finance_margin_panel',
    description: 'Painel gerencial de margem financeira.',
    squadId: 'squad-c',
    owner: 'Financas',
    status: 'in_progress',
    health: 'yellow',
    progress: 43,
    pipelineCount: 1,
    monthlyCost: 6800,
    updatedAt: '2026-04-23T14:05:00-03:00',
    linkedProjectIds: ['lup-ed-2719'],
  },
];
