import { DataDemand } from './demand.model';

export const DATA_DEMANDS: DataDemand[] = [
  {
    id: 'demand-2741',
    code: 'DEM-2741',
    title: 'Customer 360',
    description: 'Visão consolidada de cliente para Marketing e CS, com fontes de pedidos, cadastro e eventos digitais.',
    requester: 'Mariana Silva',
    businessArea: 'Marketing',
    domain: 'Clientes',
    squadId: 'squad-b',
    status: 'approved',
    expectedTarget: 'spec.customer_360',
    sla: 'D+0 até 07h30',
    sources: ['silver.customer_base', 'silver.orders', 'bronze.clickstream'],
    createdAt: '2026-04-18T09:12:00-03:00',
    createdBy: 'mariana.silva@company.com',
    updatedAt: '2026-04-22T15:40:00-03:00',
    updatedBy: 'rafael.carvalho@company.com',
  },
  {
    id: 'demand-2736',
    code: 'DEM-2736',
    title: 'Exposição diária de risco',
    description: 'Consolidar exposição de risco por carteira para consumo de gestão e alertas diários.',
    requester: 'Renato Lima',
    businessArea: 'Risco',
    domain: 'Risco',
    squadId: 'squad-c',
    status: 'in_review',
    expectedTarget: 'spec.risk_exposure_daily',
    sla: 'D+0 até 08h00',
    sources: ['sot.positions', 'sot.counterparties'],
    createdAt: '2026-04-20T10:35:00-03:00',
    createdBy: 'renato.lima@company.com',
    updatedAt: '2026-04-25T16:05:00-03:00',
    updatedBy: 'squad-c@company.com',
  },
  {
    id: 'demand-2708',
    code: 'DEM-2708',
    title: 'Reconstrução bronze de pedidos',
    description: 'Revisar ingestão de pedidos para corrigir histórico, lineage e janelas de reprocessamento.',
    requester: 'Paula Martins',
    businessArea: 'Comercial',
    domain: 'Pedidos',
    squadId: 'squad-a',
    status: 'active',
    expectedTarget: 'sor.orders',
    sla: 'Até 30 min após disponibilidade na origem',
    sources: ['rds.orders_db.orders', 'rds.orders_db.order_items'],
    createdAt: '2026-04-12T14:00:00-03:00',
    createdBy: 'paula.martins@company.com',
    updatedAt: '2026-04-21T11:15:00-03:00',
    updatedBy: 'squad-a@company.com',
  },
  {
    id: 'demand-2769',
    code: 'DEM-2769',
    title: 'Cartão — Visão de fatura mensal',
    description: 'Painel mensal com fatura, parcelamentos e benefícios por cliente para canais digitais.',
    requester: 'Letícia Aguiar',
    businessArea: 'Cartões',
    domain: 'Cartões',
    squadId: 'squad-c',
    status: 'active',
    expectedTarget: 'gold.cartao_fatura_mensal',
    sla: 'D-1 até 06h00',
    sources: ['silver.cartao_fatura', 'silver.cartao_uso'],
    createdAt: '2026-04-23T08:50:00-03:00',
    createdBy: 'leticia.aguiar@company.com',
    updatedAt: '2026-04-26T09:30:00-03:00',
    updatedBy: 'leticia.aguiar@company.com',
  },
  {
    id: 'demand-2780',
    code: 'DEM-2780',
    title: 'KPIs de marketing diário',
    description: 'Mart com indicadores de campanha, atribuição e custo de aquisição por canal.',
    requester: 'Felipe Souza',
    businessArea: 'Marketing',
    domain: 'Marketing',
    squadId: 'squad-b',
    status: 'cancelled',
    expectedTarget: 'mart.kpi_marketing_daily',
    sla: 'D-1 até 09h00',
    sources: ['silver.campaigns', 'bronze.clickstream'],
    createdAt: '2026-03-30T15:42:00-03:00',
    createdBy: 'felipe.souza@company.com',
    updatedAt: '2026-04-08T10:12:00-03:00',
    updatedBy: 'felipe.souza@company.com',
    cancelledAt: '2026-04-08T10:12:00-03:00',
    cancelledBy: 'felipe.souza@company.com',
    cancelReason: 'Atendido pelo job legado existente; demanda redirecionada.',
  },
  {
    id: 'demand-2792',
    code: 'DEM-2792',
    title: 'IoT — Detecção de anomalias',
    description: 'Score de anomalia em sensores industriais com janela móvel de 7 dias.',
    requester: 'Beatriz Lima',
    businessArea: 'Operações',
    domain: 'IoT',
    squadId: 'squad-c',
    status: 'in_review',
    expectedTarget: 'silver.iot_sensor_anomaly',
    sla: 'A cada 5 min',
    sources: ['kinesis.iot_stream'],
    createdAt: '2026-04-22T13:00:00-03:00',
    createdBy: 'beatriz.lima@company.com',
    updatedAt: '2026-04-26T07:20:00-03:00',
    updatedBy: 'rafael.carvalho@company.com',
  },
  {
    id: 'demand-2801',
    code: 'DEM-2801',
    title: 'Recomendação de bundles de produto',
    description: 'Discovery em SQL para validar correlação entre bundles e ticket médio. Sem deploy produtivo.',
    requester: 'Ana Reis',
    businessArea: 'Comercial',
    domain: 'Produto',
    squadId: 'squad-b',
    status: 'active',
    expectedTarget: 'spec.product_bundle_recommendation',
    sla: 'Sob demanda — discovery',
    sources: ['silver.orders', 'silver.products'],
    createdAt: '2026-04-19T11:05:00-03:00',
    createdBy: 'ana.reis@company.com',
    updatedAt: '2026-04-24T15:18:00-03:00',
    updatedBy: 'ana.reis@company.com',
  },
];
