import { DataDemand } from './demand.model';

export const DATA_DEMANDS: DataDemand[] = [
  {
    id: 'demand-2741',
    code: 'DEM-2741',
    title: 'Customer 360',
    description: 'Visao consolidada de cliente para Marketing e CS, com fontes de pedidos, cadastro e eventos digitais.',
    requester: 'Mariana Silva',
    businessArea: 'Marketing',
    domain: 'Clientes',
    squadId: 'squad-b',
    status: 'approved',
    expectedTarget: 'spec.customer_360',
    sla: 'D+0 ate 07h30',
    sources: ['silver.customer_base', 'silver.orders', 'bronze.clickstream'],
    createdAt: '2026-04-18T09:12:00-03:00',
    createdBy: 'mariana.silva@company.com',
    updatedAt: '2026-04-22T15:40:00-03:00',
    updatedBy: 'rafael.carvalho@company.com',
  },
  {
    id: 'demand-2736',
    code: 'DEM-2736',
    title: 'Exposicao diaria de risco',
    description: 'Consolidar exposicao de risco por carteira para consumo de gestao e alertas diarios.',
    requester: 'Renato Lima',
    businessArea: 'Risco',
    domain: 'Risco',
    squadId: 'squad-c',
    status: 'in_review',
    expectedTarget: 'spec.risk_exposure_daily',
    sla: 'D+0 ate 08h00',
    sources: ['sot.positions', 'sot.counterparties'],
    createdAt: '2026-04-20T10:35:00-03:00',
    createdBy: 'renato.lima@company.com',
    updatedAt: '2026-04-25T16:05:00-03:00',
    updatedBy: 'squad-c@company.com',
  },
  {
    id: 'demand-2708',
    code: 'DEM-2708',
    title: 'Reconstrucao bronze de pedidos',
    description: 'Revisar ingestao de pedidos para corrigir historico, lineage e janelas de reprocessamento.',
    requester: 'Paula Martins',
    businessArea: 'Comercial',
    domain: 'Pedidos',
    squadId: 'squad-a',
    status: 'active',
    expectedTarget: 'sor.orders',
    sla: 'Ate 30 min apos disponibilidade na origem',
    sources: ['rds.orders_db.orders', 'rds.orders_db.order_items'],
    createdAt: '2026-04-12T14:00:00-03:00',
    createdBy: 'paula.martins@company.com',
    updatedAt: '2026-04-21T11:15:00-03:00',
    updatedBy: 'squad-a@company.com',
  },
];
