import { PipelineSensorBinding, PipelineWaitingItem, Sensor, SensorState } from './sensor.model';

const NOW = '2026-04-26T07:30:00-03:00';
const ago = (mins: number) => new Date(Date.parse(NOW) - mins * 60_000).toISOString();
const inMins = (mins: number) => new Date(Date.parse(NOW) + mins * 60_000).toISOString();

export const SENSORS: Sensor[] = [
  {
    id: 'sens-orders-rds',
    name: 'orders RDS freshness',
    description: 'Verifica se a tabela orders.rds foi atualizada nos últimos 30 min.',
    sourceQualifiedName: 'rds.orders_db.orders',
    query: "SELECT 1 FROM orders_db.orders WHERE updated_at >= current_timestamp - interval '30' minute LIMIT 1",
    intervalMinutes: 15,
    freshnessThresholdMinutes: 30,
    ownerSquadId: 'squad-a',
    enabled: true,
    createdAt: '2026-03-01T00:00:00-03:00', updatedAt: '2026-04-20T00:00:00-03:00',
  },
  {
    id: 'sens-clickstream-kinesis',
    name: 'clickstream Kinesis liveness',
    description: 'Confere se o stream Kinesis recebeu eventos nos últimos 5 min.',
    sourceQualifiedName: 'kinesis.clickstream_stream',
    query: "SELECT 1 FROM clickstream_raw WHERE event_timestamp >= current_timestamp - interval '5' minute LIMIT 1",
    intervalMinutes: 5,
    freshnessThresholdMinutes: 10,
    ownerSquadId: 'squad-a',
    enabled: true,
    createdAt: '2026-03-15T00:00:00-03:00', updatedAt: NOW,
  },
  {
    id: 'sens-customer-base',
    name: 'sot customer_base',
    description: 'Garante que sot.customer_base foi consolidado antes do customer_360.',
    sourceQualifiedName: 'sot.customer_base',
    query: "SELECT 1 FROM sot.customer_base WHERE snapshot_at = current_date LIMIT 1",
    intervalMinutes: 30,
    freshnessThresholdMinutes: 90,
    ownerSquadId: 'squad-b',
    enabled: true,
    createdAt: '2026-02-15T00:00:00-03:00', updatedAt: '2026-04-22T00:00:00-03:00',
  },
  {
    id: 'sens-finance-summary',
    name: 'spec financial_summary',
    description: 'Pré-requisito do export para RDS de relatórios financeiros.',
    sourceQualifiedName: 'spec.financial_summary',
    query: "SELECT 1 FROM spec.financial_summary WHERE generated_at >= current_date LIMIT 1",
    intervalMinutes: 30,
    freshnessThresholdMinutes: 60,
    ownerSquadId: 'squad-c',
    enabled: false,
    createdAt: '2026-01-12T00:00:00-03:00', updatedAt: '2026-04-10T00:00:00-03:00',
  },
  {
    id: 'sens-order-items-rds',
    name: 'order_items RDS freshness',
    description: 'Verifica se itens de pedido chegaram na origem relacional.',
    sourceQualifiedName: 'rds.orders_db.order_items',
    query: "SELECT 1 FROM orders_db.order_items WHERE updated_at >= current_timestamp - interval '30' minute LIMIT 1",
    intervalMinutes: 15,
    freshnessThresholdMinutes: 30,
    ownerSquadId: 'squad-a',
    enabled: true,
    createdAt: '2026-03-01T00:00:00-03:00', updatedAt: NOW,
  },
  {
    id: 'sens-sot-orders',
    name: 'sot orders snapshot',
    description: 'Confirma a harmonização diária de pedidos em SOT.',
    sourceQualifiedName: 'sot.orders',
    query: "SELECT 1 FROM sot.orders WHERE reference_date = current_date LIMIT 1",
    intervalMinutes: 30,
    freshnessThresholdMinutes: 90,
    ownerSquadId: 'squad-b',
    enabled: true,
    createdAt: '2026-03-18T00:00:00-03:00', updatedAt: NOW,
  },
  {
    id: 'sens-sor-crm-contacts',
    name: 'sor crm_contacts',
    description: 'Confirma carga incremental de contatos do CRM.',
    sourceQualifiedName: 'sor.crm_contacts',
    query: "SELECT 1 FROM sor.crm_contacts WHERE ingestion_date = current_date LIMIT 1",
    intervalMinutes: 30,
    freshnessThresholdMinutes: 120,
    ownerSquadId: 'squad-b',
    enabled: true,
    createdAt: '2026-03-20T00:00:00-03:00', updatedAt: NOW,
  },
  {
    id: 'sens-sor-clickstream-daily',
    name: 'sor clickstream daily partition',
    description: 'Confirma presença da partição diária de eventos digitais.',
    sourceQualifiedName: 'sor.clickstream',
    query: "SELECT 1 FROM sor.clickstream WHERE event_date = current_date LIMIT 1",
    intervalMinutes: 20,
    freshnessThresholdMinutes: 45,
    ownerSquadId: 'squad-a',
    enabled: true,
    createdAt: '2026-03-22T00:00:00-03:00', updatedAt: NOW,
  },
  {
    id: 'sens-sor-product-feed',
    name: 'sor product_feed',
    description: 'Confirma carga diária do catálogo bruto de produtos.',
    sourceQualifiedName: 'sor.product_feed',
    query: "SELECT 1 FROM sor.product_feed WHERE batch_date = current_date LIMIT 1",
    intervalMinutes: 30,
    freshnessThresholdMinutes: 120,
    ownerSquadId: 'squad-b',
    enabled: true,
    createdAt: '2026-03-25T00:00:00-03:00', updatedAt: NOW,
  },
  {
    id: 'sens-sor-product-attributes',
    name: 'sor product_attributes',
    description: 'Confirma disponibilidade dos atributos de produto.',
    sourceQualifiedName: 'sor.product_attributes',
    query: "SELECT 1 FROM sor.product_attributes WHERE batch_date = current_date LIMIT 1",
    intervalMinutes: 30,
    freshnessThresholdMinutes: 120,
    ownerSquadId: 'squad-b',
    enabled: true,
    createdAt: '2026-03-25T00:00:00-03:00', updatedAt: NOW,
  },
  {
    id: 'sens-sot-products',
    name: 'sot products',
    description: 'Confirma harmonização do domínio de produtos.',
    sourceQualifiedName: 'sot.products',
    query: "SELECT 1 FROM sot.products WHERE reference_date = current_date LIMIT 1",
    intervalMinutes: 30,
    freshnessThresholdMinutes: 120,
    ownerSquadId: 'squad-b',
    enabled: true,
    createdAt: '2026-03-28T00:00:00-03:00', updatedAt: NOW,
  },
  {
    id: 'sens-spec-financial-transactions',
    name: 'sot financial_transactions',
    description: 'Confirma transações financeiras harmonizadas para o export.',
    sourceQualifiedName: 'sot.financial_transactions',
    query: "SELECT 1 FROM sot.financial_transactions WHERE accounting_date = current_date LIMIT 1",
    intervalMinutes: 30,
    freshnessThresholdMinutes: 60,
    ownerSquadId: 'squad-c',
    enabled: true,
    createdAt: '2026-03-28T00:00:00-03:00', updatedAt: NOW,
  },
  {
    id: 'sens-sor-erp-master',
    name: 'sor erp_master',
    description: 'Confirma sincronização de dados mestre do ERP.',
    sourceQualifiedName: 'sor.erp_master',
    query: "SELECT 1 FROM sor.erp_master WHERE batch_date = current_date LIMIT 1",
    intervalMinutes: 60,
    freshnessThresholdMinutes: 180,
    ownerSquadId: 'squad-c',
    enabled: true,
    createdAt: '2026-04-01T00:00:00-03:00', updatedAt: NOW,
  },
  {
    id: 'sens-iot-kinesis',
    name: 'iot Kinesis liveness',
    description: 'Confere se o stream de sensores recebeu eventos recentes.',
    sourceQualifiedName: 'kinesis.iot_stream',
    query: "SELECT 1 FROM iot_sensor_raw WHERE event_timestamp >= current_timestamp - interval '5' minute LIMIT 1",
    intervalMinutes: 5,
    freshnessThresholdMinutes: 10,
    ownerSquadId: 'squad-c',
    enabled: true,
    createdAt: '2026-04-02T00:00:00-03:00', updatedAt: NOW,
  },
];

export const SENSOR_STATES: SensorState[] = [
  { sensorId: 'sens-orders-rds',         status: 'green',  lastResult: 1, lastRunAt: ago(8),   lastLatencyMs: 142,  nextRunAt: inMins(7) },
  { sensorId: 'sens-clickstream-kinesis', status: 'yellow', lastResult: 0, lastRunAt: ago(12), lastLatencyMs: 215,  nextRunAt: inMins(0), errorMessage: 'Stream sem eventos há 12 min — limite 10 min.' },
  { sensorId: 'sens-customer-base',      status: 'red',    lastResult: 0, lastRunAt: ago(150), lastLatencyMs: 4002, nextRunAt: inMins(20), errorMessage: 'Falha ao consultar — verifique role do motor.' },
  { sensorId: 'sens-finance-summary',    status: 'gray',   lastResult: 0 },
  { sensorId: 'sens-order-items-rds',     status: 'yellow', lastResult: 0, lastRunAt: ago(16),  lastLatencyMs: 188,  nextRunAt: inMins(4) },
  { sensorId: 'sens-sot-orders',          status: 'green',  lastResult: 1, lastRunAt: ago(10),  lastLatencyMs: 260,  nextRunAt: inMins(20) },
  { sensorId: 'sens-sor-crm-contacts',    status: 'green',  lastResult: 1, lastRunAt: ago(24),  lastLatencyMs: 311,  nextRunAt: inMins(6) },
  { sensorId: 'sens-sor-clickstream-daily', status: 'green', lastResult: 1, lastRunAt: ago(6),  lastLatencyMs: 102,  nextRunAt: inMins(14) },
  { sensorId: 'sens-sor-product-feed',    status: 'green',  lastResult: 1, lastRunAt: ago(32),  lastLatencyMs: 450,  nextRunAt: inMins(28) },
  { sensorId: 'sens-sor-product-attributes', status: 'green', lastResult: 1, lastRunAt: ago(34), lastLatencyMs: 490, nextRunAt: inMins(26) },
  { sensorId: 'sens-sot-products',        status: 'green',  lastResult: 1, lastRunAt: ago(18),  lastLatencyMs: 520,  nextRunAt: inMins(12) },
  { sensorId: 'sens-spec-financial-transactions', status: 'green', lastResult: 1, lastRunAt: ago(20), lastLatencyMs: 670, nextRunAt: inMins(10) },
  { sensorId: 'sens-sor-erp-master',      status: 'green',  lastResult: 1, lastRunAt: ago(40),  lastLatencyMs: 760,  nextRunAt: inMins(20) },
  { sensorId: 'sens-iot-kinesis',         status: 'green',  lastResult: 1, lastRunAt: ago(3),   lastLatencyMs: 94,   nextRunAt: inMins(2) },
];

export const PIPELINE_BINDINGS: PipelineSensorBinding[] = [
  {
    pipelineId: 'pipeline-2',
    pipelineName: 'transform_customer_360',
    sensorIds: ['sens-customer-base', 'sens-orders-rds', 'sens-sot-orders', 'sens-sor-crm-contacts', 'sens-sor-clickstream-daily'],
    failureAction: 'stop',
    maxWaitMinutes: 120,
    updatedAt: '2026-04-21T00:00:00-03:00', updatedBy: 'rafael.carvalho',
  },
  {
    pipelineId: 'pipeline-3',
    pipelineName: 'export_financial_reporting',
    sensorIds: ['sens-finance-summary', 'sens-spec-financial-transactions'],
    failureAction: 'alert',
    maxWaitMinutes: 60,
    updatedAt: '2026-04-15T00:00:00-03:00', updatedBy: 'thais.borges',
  },
  {
    pipelineId: 'pipeline-1',
    pipelineName: 'ingestion_orders',
    sensorIds: ['sens-orders-rds', 'sens-order-items-rds'],
    failureAction: 'proceed',
    maxWaitMinutes: 30,
    updatedAt: '2026-04-25T00:00:00-03:00', updatedBy: 'rafael.carvalho',
  },
  {
    pipelineId: 'pipeline-5',
    pipelineName: 'orchestration_daily_full',
    sensorIds: ['sens-orders-rds', 'sens-sot-orders', 'sens-sor-crm-contacts', 'sens-sor-clickstream-daily', 'sens-sor-product-feed', 'sens-sor-product-attributes'],
    failureAction: 'stop',
    maxWaitMinutes: 180,
    updatedAt: '2026-04-25T00:00:00-03:00', updatedBy: 'rafael.carvalho',
  },
  {
    pipelineId: 'pipeline-7',
    pipelineName: 'harmonize_product_catalog',
    sensorIds: ['sens-sor-product-feed', 'sens-sor-product-attributes'],
    failureAction: 'alert',
    maxWaitMinutes: 90,
    updatedAt: '2026-04-25T00:00:00-03:00', updatedBy: 'beatriz.lima',
  },
  {
    pipelineId: 'pipeline-8',
    pipelineName: 'ingestion_iot_sensors',
    sensorIds: ['sens-iot-kinesis'],
    failureAction: 'proceed',
    maxWaitMinutes: 10,
    updatedAt: '2026-04-25T00:00:00-03:00', updatedBy: 'beatriz.lima',
  },
  {
    pipelineId: 'pipeline-9',
    pipelineName: 'sync_erp_master_data',
    sensorIds: ['sens-sor-erp-master'],
    failureAction: 'alert',
    maxWaitMinutes: 120,
    updatedAt: '2026-04-25T00:00:00-03:00', updatedBy: 'thais.borges',
  },
];

export const WAITING_PIPELINES: PipelineWaitingItem[] = [
  {
    pipelineId: 'pipeline-2',
    pipelineName: 'transform_customer_360',
    waitingSensorId: 'sens-customer-base',
    waitingSensorName: 'sot customer_base',
    waitingSourceTable: 'sot.customer_base',
    waitingForMinutes: 92,
    slaMinutes: 120,
  },
  {
    pipelineId: 'pipeline-3',
    pipelineName: 'export_financial_reporting',
    waitingSensorId: 'sens-finance-summary',
    waitingSensorName: 'spec financial_summary',
    waitingSourceTable: 'spec.financial_summary',
    waitingForMinutes: 18,
    slaMinutes: 60,
  },
];
