import { ProjectJourney } from './project-journey.store';

/**
 * Mocks de jornadas de projeto. Usados pela tela "Jornadas" (consulta) e
 * pela "Visão do Desenvolvedor" para popular as listas de em-andamento /
 * concluídas / deletadas. Estados terminais (completed/deleted) preservam
 * histórico e aparecem na consulta.
 *
 * Tipagem completa por campo evita drift com o modelo. Quando vier
 * backend real, este arquivo desaparece — o store passa a fazer fetch.
 */
export const PROJECT_JOURNEYS_SEED: ProjectJourney[] = [
  {
    id: 'pj-customer-360',
    name: 'customer_360',
    templateId: 'glue-pyspark',
    status: 'active',
    createdAt: '2026-04-15T09:30:00-03:00',
    createdBy: 'Rafael Carvalho',
    updatedAt: '2026-04-26T10:14:00-03:00',
    importedDemandId: 'demand-1',
    importedDemandCode: 'DEM-00012',
    lupCodes: ['ED2741'],
    targetTable: 'gold.customer_360',
    responsible: 'Rafael Carvalho',
    squadId: 'squad-b',
    domain: 'Comercial',
    currentStage: 'Infra de sandbox Glue',
    progress: 38,
  },
  {
    id: 'pj-risk-exposure',
    name: 'risk_exposure_daily',
    templateId: 'glue-pyspark',
    status: 'active',
    createdAt: '2026-04-04T14:10:00-03:00',
    createdBy: 'Thais Borges',
    updatedAt: '2026-04-25T18:00:00-03:00',
    importedDemandCode: 'DEM-00009',
    lupCodes: ['ED2736'],
    targetTable: 'gold.risk_exposure_daily',
    responsible: 'Thais Borges',
    squadId: 'squad-c',
    domain: 'Risco',
    currentStage: 'Deploy Dev / Homologação',
    progress: 71,
  },
  {
    id: 'pj-finance-curated',
    name: 'finance_curated_v2',
    templateId: 'glue-pyspark',
    status: 'completed',
    createdAt: '2026-02-12T08:00:00-03:00',
    createdBy: 'Murilo Tavares',
    updatedAt: '2026-04-08T11:30:00-03:00',
    importedDemandCode: 'DEM-00005',
    lupCodes: ['ED2719', 'EA1102'],
    targetTable: 'gold.finance_curated_v2',
    responsible: 'Murilo Tavares',
    squadId: 'squad-c',
    domain: 'Financeiro',
    currentStage: 'Documentação',
    progress: 100,
  },
  {
    id: 'pj-iot-anomaly',
    name: 'iot_sensor_anomaly',
    templateId: 'glue-pyspark',
    status: 'active',
    createdAt: '2026-04-22T16:45:00-03:00',
    createdBy: 'Beatriz Lima',
    updatedAt: '2026-04-26T09:00:00-03:00',
    importedDemandCode: 'DEM-00014',
    lupCodes: ['ED2756'],
    targetTable: 'silver.iot_sensor_anomaly',
    responsible: 'Beatriz Lima',
    squadId: 'squad-c',
    domain: 'Operações',
    currentStage: 'Requisitos da demanda',
    progress: 9,
  },
  {
    id: 'pj-marketing-kpis',
    name: 'kpi_marketing_daily',
    templateId: 'sql-only',
    status: 'completed',
    createdAt: '2026-01-08T10:20:00-03:00',
    createdBy: 'Felipe Souza',
    updatedAt: '2026-03-12T17:40:00-03:00',
    importedDemandCode: 'DEM-00002',
    lupCodes: ['ED2701'],
    targetTable: 'mart.kpi_marketing_daily',
    responsible: 'Felipe Souza',
    squadId: 'squad-b',
    domain: 'Marketing',
    currentStage: 'Documentação',
    progress: 100,
  },
  {
    id: 'pj-product-bundle',
    name: 'product_bundle_discovery',
    templateId: 'sql-only',
    status: 'active',
    createdAt: '2026-04-19T11:05:00-03:00',
    createdBy: 'Ana Reis',
    updatedAt: '2026-04-24T15:18:00-03:00',
    lupCodes: ['EA1180'],
    targetTable: 'spec.product_bundle_recommendation',
    responsible: 'Ana Reis',
    squadId: 'squad-b',
    domain: 'Comercial',
    currentStage: 'Workspace SQL',
    progress: 22,
  },
  {
    id: 'pj-erp-master',
    name: 'sync_erp_master_data',
    templateId: 'glue-pyspark',
    status: 'deleted',
    createdAt: '2026-03-26T13:50:00-03:00',
    createdBy: 'Rafael Carvalho',
    updatedAt: '2026-04-02T09:10:00-03:00',
    deletedAt: '2026-04-02T09:10:00-03:00',
    deletedBy: 'Rafael Carvalho',
    importedDemandCode: 'DEM-00007',
    lupCodes: ['ED2724'],
    targetTable: 'bronze.erp_master',
    responsible: 'Rafael Carvalho',
    squadId: 'squad-c',
    domain: 'Operações',
    currentStage: 'Cancelada após realinhamento da arquitetura',
    progress: 14,
  },
];
