import { Capability, Role, ScopeLevel } from './access.types';

export const AD_GROUP_PREFIX = 'dp';

const join = (...parts: string[]) => [AD_GROUP_PREFIX, ...parts].join('.');

export const AD_GROUP_PATTERNS = {
  role: (role: Role) => join('role', role),
  scope: (level: ScopeLevel, id: string) => join('scope', level, id),
};

export const DEFAULT_ROLE_CAPABILITIES: Record<Role, Capability[]> = {
  'public-viewer': [
    'catalog.viewBasic',
    'demand.viewOwn',
    'demand.create',
    'demand.cancel',
  ],
  'developer': [
    'catalog.view',
    'pipeline.view',
    'pipeline.create',
    'pipeline.useTemplate.glue-pyspark',
    'pipeline.useTemplate.sql-only',
    'lineage.view',
    'dataQuality.view',
    'dev.viewProjects',
    'dev.manageLups',
    'demand.viewOwn',
    'demand.create',
    'demand.cancel',
  ],
  'techlead': [
    'catalog.view',
    'pipeline.view',
    'pipeline.create',
    'pipeline.useTemplate.glue-pyspark',
    'pipeline.useTemplate.sql-only',
    'pipeline.approveStage',
    'pipeline.codeReview',
    'pipeline.manageRegistry',
    'lineage.view',
    'dataQuality.view',
    'dev.viewProjects',
    'dev.linkLups',
    'dev.manageLups',
    'demand.viewOwn',
    'demand.create',
    'demand.cancel',
    'demand.inactivate',
  ],
  'coordinator': [
    'catalog.view',
    'pipeline.view',
    'pipeline.manageRegistry',
    'pipeline.viewCosts',
    'lineage.view',
    'dataQuality.view',
    'dev.viewProjects',
    'dev.manageLups',
    'demand.viewOwn',
    'demand.create',
    'demand.cancel',
    'demand.inactivate',
    'executive.viewOwnScope',
    'ops.viewBoard',
  ],
  'manager': [
    'catalog.view',
    'pipeline.view',
    'pipeline.manageRegistry',
    'pipeline.viewCosts',
    'lineage.view',
    'dataQuality.view',
    'dev.viewProjects',
    'dev.manageLups',
    'demand.viewOwn',
    'demand.create',
    'demand.cancel',
    'demand.inactivate',
    'executive.viewOwnScope',
    'ops.viewBoard',
    'admin.viewAudit',
  ],
  'platform-admin': [
    'catalog.view',
    'pipeline.view',
    'pipeline.create',
    'pipeline.useTemplate.glue-pyspark',
    'pipeline.useTemplate.sql-only',
    'pipeline.approveStage',
    'pipeline.codeReview',
    'pipeline.manageRegistry',
    'pipeline.viewCosts',
    'lineage.view',
    'dataQuality.view',
    'dev.viewProjects',
    'dev.linkLups',
    'dev.manageLups',
    'demand.viewOwn',
    'demand.create',
    'demand.cancel',
    'demand.inactivate',
    'executive.viewOwnScope',
    'executive.viewGlobal',
    'ops.viewBoard',
    'admin.manageAccess',
    'admin.manageOrg',
    'admin.manageStages',
    'admin.viewAudit',
  ],
};

export const ROLE_LABELS: Record<Role, string> = {
  'public-viewer': 'Visitante interno',
  'developer': 'Desenvolvedor',
  'techlead': 'Tech Lead',
  'coordinator': 'Coordenador',
  'manager': 'Gerente',
  'platform-admin': 'Administrador da Plataforma',
};

export const ROLE_DESCRIPTIONS: Record<Role, string> = {
  'public-viewer': 'Qualquer funcionario autenticado. Ve apenas catalogo publico e farol.',
  'developer': 'Cria e acompanha pipelines da propria squad.',
  'techlead': 'Aprova etapas e vincula projetos no escopo da propria squad.',
  'coordinator': 'Acompanha squads sob sua coordenacao.',
  'manager': 'Acompanha KPIs, custos, SLAs e auditoria do proprio escopo.',
  'platform-admin': 'Administra acesso, hierarquia organizacional e auditoria da plataforma.',
};

export const CAPABILITY_LABELS: Record<Capability, string> = {
  'catalog.viewBasic': 'Catalogo - visao basica',
  'catalog.view': 'Catalogo - visao completa',
  'pipeline.view': 'Pipelines - visualizar',
  'pipeline.create': 'Jornadas - criar projeto',
  'pipeline.useTemplate.glue-pyspark': 'Jornadas - usar template Glue PySpark',
  'pipeline.useTemplate.sql-only':     'Jornadas - usar template SQL only',
  'pipeline.approveStage': 'Jornadas - aprovar etapas',
  'pipeline.codeReview': 'Pipelines - code review',
  'pipeline.manageRegistry': 'Pipelines - gerir referencias manuais',
  'pipeline.viewCosts': 'Pipelines - visualizar custos',
  'lineage.view': 'Linhagem - visualizar',
  'dataQuality.view': 'Qualidade - visualizar',
  'dev.viewProjects': 'Projetos - listar',
  'dev.linkLups': 'Projetos - vincular EA/ED',
  'dev.manageLups': 'Projetos - gerir cadastro',
  'demand.viewOwn': 'Demandas - ver as próprias',
  'demand.create': 'Demandas - criar',
  'demand.cancel': 'Demandas - cancelar (autosserviço)',
  'demand.inactivate': 'Demandas - inativar (gestão)',
  'executive.viewOwnScope': 'Executivo - proprio escopo',
  'executive.viewGlobal': 'Executivo - global',
  'ops.viewBoard': 'Sustentacao - painel de farois',
  'admin.manageAccess': 'Admin - gerir acessos',
  'admin.manageOrg': 'Admin - gerir hierarquia',
  'admin.manageStages': 'Admin - gerir catálogo de etapas',
  'admin.viewAudit': 'Admin - consultar auditoria',
};

export const SCOPE_LEVEL_LABELS: Record<ScopeLevel, string> = {
  squad: 'Squad',
  coord: 'Coordenacao',
  gerencia: 'Gerencia',
  superintendencia: 'Superintendencia',
  diretoria: 'Diretoria',
};

export const ALL_ROLES: Role[] = [
  'public-viewer',
  'developer',
  'techlead',
  'coordinator',
  'manager',
  'platform-admin',
];

export const ALL_CAPABILITIES = Object.keys(CAPABILITY_LABELS) as Capability[];
